var TECHWAVE_PRODUCTS = [

  {
    id: 1,
    name: "Blender 1200W",
    category: "Kitchen Appliances",
    subcategory: "Blenders",
    brand: "Philips",
    price: 129.99,
    originalPrice: 179.99,
    image: "logo and bg imagies/blender.jpg",
    rating: 4.8,
    reviews: 342,
    badge: "Best Seller",
    badgeType: "hot",
    description: "1200W smart blender with 10 speed settings, self-cleaning mode, and app connectivity.",
    features: ["1200W Motor", "10 Speeds", "Self-Cleaning", "App Control", "BPA-Free"],
    inStock: true,
    detailedSpecs: {
      "Power": "1200 Watts",
      "Capacity": "1.75 Liters",
      "Speed Settings": "10 + Pulse",
      "Blade Material": "Stainless Steel 6-Blade",
      "Jar Material": "BPA-Free Tritan",
      "Dimensions": "8.5 x 7 x 16 inches",
      "Weight": "8.2 lbs",
      "Voltage": "220-240V",
      "Warranty": "2 Years",
      "Color": "Silver / Black",
      "Cord Length": "1.2m",
      "Noise Level": "< 75 dB",
      "Safety": "Overload protection, Suction feet"
    }
  },
  {
    id: 2,
    name: "Air Fryer 5.8QT",
    category: "Kitchen Appliances",
    subcategory: "Air Fryers",
    brand: "Samsung",
    price: 89.99,
    originalPrice: 129.99,
    image: "logo and bg imagies/airfryer.jpg",
    rating: 4.7,
    reviews: 518,
    badge: "40% OFF",
    badgeType: "sale",
    description: "5.8 QT digital air fryer with 8 preset cooking modes and rapid air technology.",
    features: ["5.8 QT Capacity", "8 Presets", "LED Touch", "Rapid Air", "Dishwasher Safe"],
    inStock: true,
    detailedSpecs: {
      "Capacity": "5.8 Quarts",
      "Power": "1700 Watts",
      "Temperature Range": "180°F - 400°F",
      "Timer": "60 Minutes Max",
      "Display": "LED Touchscreen",
      "Basket": "Non-stick coated",
      "Dimensions": "14 x 11 x 13 inches",
      "Weight": "13.5 lbs",
      "Voltage": "120V/220V",
      "Warranty": "1 Year",
      "Color": "Matte Black",
      "Certification": "ETL, FDA"
    }
  },
  {
    id: 3,
    name: "Espresso Machine 15 Bar",
    category: "Kitchen Appliances",
    subcategory: "Coffee Makers",
    brand: "LG",
    price: 349.99,
    originalPrice: 449.99,
    image: "logo and bg imagies/coffiemaker.jpg",
    rating: 4.9,
    reviews: 256,
    badge: "Premium",
    badgeType: "new",
    description: "Professional espresso machine with built-in grinder and barista-quality extraction.",
    features: ["Built-in Grinder", "Milk Frother", "15-Bar Pump", "PID Control", "Stainless Steel"],
    inStock: true,
    detailedSpecs: {
      "Pump Pressure": "15 Bar",
      "Power": "1450 Watts",
      "Water Tank": "2.0 Liters",
      "Grinder": "Conical Burr, 15 settings",
      "Milk System": "Automatic Frother",
      "Boiler": "Thermoblock with PID",
      "Dimensions": "12 x 10 x 15 inches",
      "Weight": "18 lbs",
      "Warranty": "2 Years",
      "Color": "Brushed Stainless Steel"
    }
  },
  {
    id: 4,
    name: "Microwave Oven 30L",
    category: "Kitchen Appliances",
    subcategory: "Microwave Ovens",
    brand: "Samsung",
    price: 199.99,
    originalPrice: 249.99,
    image: "logo and bg imagies/microwave.jpg",
    rating: 4.6,
    reviews: 189,
    badge: "Smart",
    badgeType: "new",
    description: "Smart microwave with sensor cooking, convection mode, and WiFi app control.",
    features: ["Sensor Cook", "Convection", "WiFi Control", "30L Capacity", "Grill Function"],
    inStock: true,
    detailedSpecs: {
      "Capacity": "30 Liters / 1.1 Cu.Ft",
      "Power Output": "1100 Watts",
      "Convection": "Yes, up to 450°F",
      "Grill": "1200W Quartz",
      "Programs": "12 Auto Cook",
      "Turntable": "12.4 inch Glass",
      "Display": "LED with Clock",
      "Dimensions": "21.5 x 18 x 12.8 inches",
      "Weight": "35 lbs",
      "Warranty": "1 Year",
      "Color": "Stainless Steel",
      "Connectivity": "WiFi + SmartThings App"
    }
  },
  {
    id: 5,
    name: "Stand Mixer 6QT",
    category: "Kitchen Appliances",
    subcategory: "Mixers",
    brand: "Haier",
    price: 279.99,
    originalPrice: 359.99,
    image: "logo and bg imagies/mixer.jpg",
    rating: 4.8,
    reviews: 412,
    badge: "Top Rated",
    badgeType: "hot",
    description: "Heavy-duty stand mixer with 600W motor and 6-quart bowl for all baking needs.",
    features: ["600W Motor", "6-Qt Bowl", "10 Speeds", "Tilt-Head", "3 Attachments"],
    inStock: true,
    detailedSpecs: {
      "Power": "600 Watts",
      "Bowl Capacity": "6 Quarts / 5.7 Liters",
      "Speed Settings": "10 + Slow Start",
      "Attachments": "Dough Hook, Flat Beater, Wire Whip",
      "Bowl Material": "Polished Stainless Steel",
      "Head Type": "Tilt-Head",
      "Dimensions": "14 x 9 x 14 inches",
      "Weight": "22 lbs",
      "Warranty": "2 Years",
      "Color": "Empire Red / White / Black"
    }
  },
  {
    id: 6,
    name: "Pressure Cooker 6QT",
    category: "Kitchen Appliances",
    subcategory: "Cookers",
    brand: "Dawlance",
    price: 79.99,
    originalPrice: 109.99,
    image: "logo and bg imagies/presurecooker.jpg",
    rating: 4.5,
    reviews: 634,
    badge: "Value Pick",
    badgeType: "sale",
    description: "Multi-function pressure cooker with 14 smart programs for quick meals.",
    features: ["14 Programs", "6-Qt", "Keep Warm", "Timer", "Safety Lock"],
    inStock: true,
    detailedSpecs: {
      "Capacity": "6 Quarts",
      "Power": "1000 Watts",
      "Programs": "14 Smart Presets",
      "Pressure": "10.15-11.6 PSI",
      "Inner Pot": "Non-stick Coated Aluminum",
      "Timer": "Up to 24 Hours Delay",
      "Keep Warm": "Up to 10 Hours",
      "Dimensions": "13 x 12 x 12.5 inches",
      "Weight": "14 lbs",
      "Safety": "10-Point Safety System",
      "Warranty": "1 Year",
      "Accessories": "Measuring Cup, Spoon, Steam Rack"
    }
  },

  {
    id: 7,
    name: "Robot Vacuum 2500Pa",
    category: "Home Appliances",
    subcategory: "Vacuums",
    brand: "Samsung",
    price: 399.99,
    originalPrice: 549.99,
    image: "logo and bg imagies/vacum.jpg",
    rating: 4.9,
    reviews: 723,
    badge: "Best Seller",
    badgeType: "hot",
    description: "AI-powered robot vacuum with LiDAR navigation and auto-empty station.",
    features: ["LiDAR Nav", "Auto-Empty", "2500Pa Suction", "App Control", "Alexa/Google"],
    inStock: true,
    detailedSpecs: {
      "Suction Power": "2500 Pa",
      "Navigation": "LiDAR + AI Mapping",
      "Dustbin": "400ml (Robot) + 2.5L (Station)",
      "Battery": "5200mAh Li-ion",
      "Runtime": "180 Minutes",
      "Charging Time": "4 Hours",
      "Noise Level": "55-65 dB",
      "Mopping": "Yes, Electronic Water Tank",
      "Dimensions": "13.9 x 3.8 inches",
      "Weight": "7.7 lbs",
      "Connectivity": "WiFi + App + Alexa + Google",
      "Warranty": "2 Years"
    }
  },
  {
    id: 8,
    name: "Split AC 1.5 Ton",
    category: "Home Appliances",
    subcategory: "Air Conditioners",
    brand: "Haier",
    price: 599.99,
    originalPrice: 799.99,
    image: "logo and bg imagies/ac.jpg",
    rating: 4.7,
    reviews: 345,
    badge: "Energy Star",
    badgeType: "new",
    description: "Energy-efficient inverter AC with smart WiFi control and ultra-quiet operation.",
    features: ["Inverter Tech", "WiFi Control", "4-Way Flow", "Ultra Quiet", "Auto Clean"],
    inStock: true,
    detailedSpecs: {
      "Capacity": "1.5 Ton / 18000 BTU",
      "Type": "Split Inverter",
      "Energy Rating": "5 Star / SEER 21",
      "Refrigerant": "R-410A",
      "Cooling Area": "Up to 250 sq ft",
      "Compressor": "DC Inverter Rotary",
      "Airflow": "4-Way Auto Swing",
      "Noise Indoor": "26 dB",
      "Noise Outdoor": "52 dB",
      "Power": "1350W (Cooling)",
      "Dimensions Indoor": "33.5 x 8 x 11.5 inches",
      "Warranty": "5 Years Compressor + 1 Year Parts",
      "Connectivity": "WiFi + Voice Control",
      "Features": "Self-Clean, Turbo Cool, Sleep Mode"
    }
  },
  {
    id: 9,
    name: "Front Load Washer 8kg",
    category: "Home Appliances",
    subcategory: "Washers & Dryers",
    brand: "LG",
    price: 649.99,
    originalPrice: 849.99,
    image: "logo and bg imagies/washer.jpg",
    rating: 4.8,
    reviews: 278,
    badge: "Smart Home",
    badgeType: "new",
    description: "Smart front load washer with AI cycle detection and steam clean technology.",
    features: ["AI Wash", "Steam Clean", "8kg Capacity", "App Control", "Energy A+++"],
    inStock: true,
    detailedSpecs: {
      "Capacity": "8 kg / 17.6 lbs",
      "Type": "Front Load",
      "Spin Speed": "1400 RPM Max",
      "Motor": "Direct Drive Inverter",
      "Wash Programs": "14",
      "Steam": "Yes - Allergy Care & Hygiene",
      "Energy Class": "A+++",
      "Water Usage": "48L per cycle",
      "Noise Wash": "47 dB",
      "Noise Spin": "72 dB",
      "Dimensions": "23.6 x 23.6 x 33.5 inches",
      "Weight": "154 lbs",
      "Warranty": "10 Years Motor + 2 Years Parts",
      "Smart": "WiFi + NFC + App Control"
    }
  },
  {
    id: 10,
    name: "Tower Fan 42 Inch",
    category: "Home Appliances",
    subcategory: "Fans",
    brand: "Dawlance",
    price: 149.99,
    originalPrice: 199.99,
    image: "logo and bg imagies/towerfan.jpg",
    rating: 4.6,
    reviews: 456,
    badge: "25% OFF",
    badgeType: "sale",
    description: "Bladeless tower fan with HEPA air purification and 10 speed settings.",
    features: ["Bladeless", "HEPA Filter", "10 Speeds", "Remote", "Timer"],
    inStock: true,
    detailedSpecs: {
      "Type": "Bladeless Tower",
      "Height": "42 inches",
      "Speeds": "10",
      "Oscillation": "350° Wide Range",
      "Filter": "HEPA H13",
      "Airflow": "290 L/s",
      "Timer": "1-9 Hours",
      "Noise": "35-62 dB",
      "Remote": "Yes, Magnetic",
      "Power": "56 Watts",
      "Warranty": "2 Years",
      "Color": "White / Silver"
    }
  },
  {
    id: 11,
    name: "Air Purifier 500sqft",
    category: "Home Appliances",
    subcategory: "Air Purifiers",
    brand: "Samsung",
    price: 249.99,
    originalPrice: 329.99,
    image: "logo and bg imagies/airfry1.jpg",
    rating: 4.7,
    reviews: 312,
    badge: "",
    badgeType: "",
    description: "Advanced air purifier with H13 HEPA filter and real-time air quality monitoring.",
    features: ["H13 HEPA", "Air Monitor", "Whisper Mode", "500 sq ft", "App Control"],
    inStock: true,
    detailedSpecs: {
      "Coverage": "500 sq ft",
      "CADR": "320 CFM",
      "Filter": "3-Stage: Pre-filter + H13 HEPA + Activated Carbon",
      "Sensors": "PM2.5 + VOC + Temperature + Humidity",
      "Noise Level": "24-52 dB",
      "Power": "45 Watts",
      "Filter Life": "6-12 Months",
      "Modes": "Auto, Sleep, Turbo, Manual",
      "Dimensions": "10 x 10 x 24 inches",
      "Weight": "12 lbs",
      "Warranty": "2 Years",
      "Smart": "WiFi + App + Voice Control"
    }
  },
  {
    id: 12,
    name: "Cordless Vacuum 150AW",
    category: "Home Appliances",
    subcategory: "Vacuums",
    brand: "LG",
    price: 299.99,
    originalPrice: 399.99,
    image: "logo and bg imagies/vacum1.jpg",
    rating: 4.5,
    reviews: 567,
    badge: "Popular",
    badgeType: "hot",
    description: "Lightweight cordless vacuum with 60-min runtime and LED cleaning head.",
    features: ["60 Min Runtime", "Lightweight", "Wall Mount", "HEPA Filter", "LED Head"],
    inStock: true,
    detailedSpecs: {
      "Suction": "150 AW",
      "Runtime": "Up to 60 Minutes",
      "Battery": "Removable Li-ion",
      "Charge Time": "3.5 Hours",
      "Dustbin": "0.77L",
      "Weight": "5.5 lbs",
      "Filtration": "5-Stage HEPA",
      "Modes": "Eco / Auto / Boost",
      "Accessories": "Crevice, Mini Brush, Motorized Head",
      "Warranty": "2 Years",
      "Wall Mount": "Included"
    }
  },

  {
    id: 13,
    name: "Hair Dryer 1800W",
    category: "Personal Care",
    subcategory: "Hair Care",
    brand: "Philips",
    price: 149.99,
    originalPrice: 199.99,
    image: "logo and bg imagies/dryer.jpg",
    rating: 4.8,
    reviews: 892,
    badge: "Best Seller",
    badgeType: "hot",
    description: "Ionic hair dryer with intelligent heat control and salon-quality results.",
    features: ["Ionic Tech", "1800W", "3 Speeds", "Cool Shot", "Lightweight"],
    inStock: true,
    detailedSpecs: {
      "Power": "1800 Watts",
      "Technology": "Ionic + Ceramic",
      "Heat Settings": "3",
      "Speed Settings": "2 + Cool Shot",
      "Concentrator": "2 Nozzles Included",
      "Diffuser": "Included",
      "Cord Length": "2.7m Swivel",
      "Weight": "1.3 lbs",
      "Noise": "< 78 dB",
      "Warranty": "2 Years"
    }
  },
  {
    id: 14,
    name: "Electric Shaver 3 Head",
    category: "Personal Care",
    subcategory: "Shavers",
    brand: "Philips",
    price: 89.99,
    originalPrice: 119.99,
    image: "logo and bg imagies/shaver1.jpg",
    rating: 4.6,
    reviews: 445,
    badge: "25% OFF",
    badgeType: "sale",
    description: "Premium electric shaver with titanium blades and wet/dry operation.",
    features: ["Titanium Blades", "Wet/Dry", "90 Min Battery", "Pop-up Trimmer", "Travel Lock"],
    inStock: true,
    detailedSpecs: {
      "Blades": "Titanium Coated",
      "Heads": "3 Flex Rotary",
      "Battery": "Li-ion, 90 Min Runtime",
      "Charge": "1 Hour Full",
      "Quick Charge": "5 Min = 1 Shave",
      "Waterproof": "IPX7",
      "Trimmer": "Pop-up Detail Trimmer",
      "Display": "LED Battery",
      "Accessories": "Travel Pouch, Cleaning Brush",
      "Warranty": "2 Years",
      "Weight": "6.3 oz"
    }
  },
  {
    id: 15,
    name: "Toothbrush Sonic",
    category: "Personal Care",
    subcategory: "Oral Care",
    brand: "Philips",
    price: 59.99,
    originalPrice: 79.99,
    image: "logo and bg imagies/electricbrush.jpg",
    rating: 4.7,
    reviews: 1023,
    badge: "Top Rated",
    badgeType: "hot",
    description: "Sonic toothbrush with 5 modes, pressure sensor, and app tracking.",
    features: ["5 Modes", "Sonic Clean", "App Track", "30-Day Battery", "Pressure Sensor"],
    inStock: true,
    detailedSpecs: {
      "Technology": "Sonic, 62,000 strokes/min",
      "Modes": "Clean, White, Gum Care, Sensitive, Deep Clean",
      "Timer": "2 Min Quad-Pacer",
      "Battery": "Li-ion, 30 Days",
      "Charging": "USB Magnetic",
      "Waterproof": "IPX7",
      "Heads": "2 Brush Heads Included",
      "Pressure Sensor": "Yes, LED Warning",
      "App": "Bluetooth + Real-time Tracking",
      "Warranty": "2 Years"
    }
  },
  {
    id: 16,
    name: "Trimmer 20 Length",
    category: "Personal Care",
    subcategory: "Trimmers",
    brand: "Philips",
    price: 69.99,
    originalPrice: 99.99,
    image: "logo and bg imagies/trimmer1.jpg",
    rating: 4.5,
    reviews: 334,
    badge: "30% OFF",
    badgeType: "sale",
    description: "Complete grooming kit with precision trimmer and 20 length settings.",
    features: ["20 Settings", "Steel Blades", "Cordless", "120 Min Runtime", "Travel Case"],
    inStock: true,
    detailedSpecs: {
      "Blades": "Self-Sharpening Stainless Steel",
      "Length Settings": "20 (0.5mm - 10mm)",
      "Runtime": "120 Minutes",
      "Charge Time": "1 Hour",
      "Motor": "DualCut Technology",
      "Waterproof": "IPX5 Washable",
      "Attachments": "3 Combs + Nose Trimmer + Detail Trimmer",
      "Display": "LED Battery Indicator",
      "Warranty": "2 Years",
      "Includes": "Travel Case, Cleaning Brush, Oil"
    }
  },
  {
    id: 17,
    name: "Facial Steamer Nano",
    category: "Personal Care",
    subcategory: "Facial Care",
    brand: "Haier",
    price: 44.99,
    originalPrice: 59.99,
    image: "logo and bg imagies/steamer1.jpg",
    rating: 4.4,
    reviews: 267,
    badge: "",
    badgeType: "",
    description: "Nano-ionic facial steamer for deep cleansing and spa-like experience.",
    features: ["Nano-Ionic", "200ml Tank", "Auto Shutoff", "Quiet", "Quick Steam"],
    inStock: true,
    detailedSpecs: {
      "Technology": "Nano-Ionic Steam",
      "Tank": "200ml",
      "Steam Time": "20-30 Minutes",
      "Heat Up": "30 Seconds",
      "Auto Shutoff": "Yes, when water runs out",
      "Noise": "< 40 dB",
      "Power": "280 Watts",
      "Dimensions": "6 x 6 x 8 inches",
      "Weight": "1.8 lbs",
      "Warranty": "1 Year"
    }
  },
  {
    id: 18,
    name: "Hair Straightener Ceramic",
    category: "Personal Care",
    subcategory: "Hair Care",
    brand: "Philips",
    price: 79.99,
    originalPrice: 109.99,
    image: "logo and bg imagies/strightner.jpg",
    rating: 4.6,
    reviews: 556,
    badge: "Popular",
    badgeType: "hot",
    description: "Ceramic flat iron with adjustable temperature and instant heat-up.",
    features: ["Ceramic Plates", "450°F Max", "LCD Display", "Dual Voltage", "Auto Shutoff"],
    inStock: true,
    detailedSpecs: {
      "Plates": "1-inch Ceramic Tourmaline",
      "Temperature": "250°F - 450°F",
      "Heat Up": "15 Seconds",
      "Display": "Digital LCD",
      "Voltage": "Dual 110-240V",
      "Auto Shutoff": "60 Minutes",
      "Swivel Cord": "8 ft 360°",
      "Weight": "0.75 lbs",
      "Plate Lock": "Yes",
      "Warranty": "2 Years"
    }
  },

  {
    id: 19,
    name: "LED TV 55 Inch 4K",
    category: "Entertainment",
    subcategory: "Televisions",
    brand: "Samsung",
    price: 699.99,
    originalPrice: 999.99,
    image: "logo and bg imagies/tv.jpg",
    rating: 4.9,
    reviews: 1456,
    badge: "30% OFF",
    badgeType: "sale",
    description: "55-inch 4K HDR smart TV with Dolby Vision and voice control.",
    features: ["4K HDR", "Dolby Vision", "Smart OS", "Voice Control", "3 HDMI"],
    inStock: true,
    detailedSpecs: {
      "Screen Size": "55 inches",
      "Resolution": "3840 x 2160 (4K UHD)",
      "Panel": "LED / VA",
      "HDR": "HDR10+ / Dolby Vision / HLG",
      "Refresh Rate": "120Hz",
      "Smart Platform": "Tizen OS",
      "Speakers": "20W 2.0 Channel",
      "Audio": "Dolby Atmos",
      "HDMI": "3x HDMI 2.1",
      "USB": "2x USB",
      "WiFi": "WiFi 5 + Bluetooth 5.0",
      "Dimensions": "48.8 x 28.2 x 2.4 inches",
      "Weight": "30.8 lbs",
      "Warranty": "2 Years"
    }
  },
  {
    id: 20,
    name: "Soundbar 5.1 Channel",
    category: "Entertainment",
    subcategory: "Speakers",
    brand: "LG",
    price: 249.99,
    originalPrice: 349.99,
    image: "logo and bg imagies/speaker.jpg",
    rating: 4.8,
    reviews: 678,
    badge: "Best Seller",
    badgeType: "hot",
    description: "5.1 surround soundbar with wireless subwoofer and Dolby Atmos.",
    features: ["5.1 Surround", "Dolby Atmos", "Bluetooth 5.3", "Wireless Sub", "Wall Mount"],
    inStock: true,
    detailedSpecs: {
      "Channels": "5.1.2",
      "Total Power": "440W",
      "Soundbar Power": "320W",
      "Subwoofer Power": "120W Wireless",
      "Audio Format": "Dolby Atmos, DTS:X",
      "Connectivity": "HDMI eARC, Optical, Bluetooth 5.3, WiFi",
      "HDMI": "1 In + 1 Out (eARC)",
      "Dimensions Bar": "39 x 2.2 x 3.4 inches",
      "Wall Mountable": "Yes, Bracket Included",
      "Warranty": "1 Year"
    }
  },
  {
    id: 21,
    name: "Headphones ANC Wireless",
    category: "Entertainment",
    subcategory: "Headphones",
    brand: "Samsung",
    price: 199.99,
    originalPrice: 279.99,
    image: "logo and bg imagies/headphone1.jpg",
    rating: 4.7,
    reviews: 2341,
    badge: "Top Rated",
    badgeType: "hot",
    description: "Premium over-ear headphones with ANC, 40-hour battery, and Hi-Res audio.",
    features: ["ANC", "40Hr Battery", "Hi-Res Audio", "Foldable", "Multipoint"],
    inStock: true,
    detailedSpecs: {
      "Driver": "40mm Dynamic",
      "Frequency": "4Hz - 40kHz (Hi-Res)",
      "ANC": "Adaptive Noise Cancellation",
      "Battery": "40 Hours (ANC On)",
      "Quick Charge": "3 Min = 1 Hour Playback",
      "Bluetooth": "5.3 with LDAC",
      "Multipoint": "2 Devices Simultaneous",
      "Weight": "8.9 oz",
      "Foldable": "Yes, Flat-Fold",
      "Microphone": "4 Beamforming Mics",
      "Carrying Case": "Included",
      "Warranty": "1 Year"
    }
  },
  {
    id: 22,
    name: "Bluetooth Speaker Portable",
    category: "Entertainment",
    subcategory: "Speakers",
    brand: "LG",
    price: 79.99,
    originalPrice: 109.99,
    image: "logo and bg imagies/speaker1.jpg",
    rating: 4.6,
    reviews: 1567,
    badge: "27% OFF",
    badgeType: "sale",
    description: "Waterproof portable speaker with 360° sound and 24-hour battery.",
    features: ["IPX7 Waterproof", "360° Sound", "24Hr Battery", "Party Mode", "USB-C"],
    inStock: true,
    detailedSpecs: {
      "Drivers": "2x 55mm Woofer + 2x 20mm Tweeter",
      "Output": "30W RMS",
      "Battery": "24 Hours Playback",
      "Charging": "USB-C, 4 Hours",
      "Waterproof": "IPX7 - 30 min at 1m depth",
      "Bluetooth": "5.3",
      "Multi-Speaker": "Yes, Party Mode up to 100",
      "Dimensions": "7.5 x 3.5 inches",
      "Weight": "1.5 lbs",
      "Mic": "Built-in for calls",
      "Warranty": "1 Year"
    }
  },
  {
    id: 23,
    name: "Gaming Console 4K",
    category: "Entertainment",
    subcategory: "Gaming",
    brand: "Samsung",
    price: 499.99,
    originalPrice: 549.99,
    image: "logo and bg imagies/gaming.jpg",
    rating: 4.9,
    reviews: 3456,
    badge: "New",
    badgeType: "new",
    description: "Next-gen gaming console with 4K at 120fps and ray tracing support.",
    features: ["4K 120fps", "1TB SSD", "Ray Tracing", "WiFi 6E", "Backward Compatible"],
    inStock: true,
    detailedSpecs: {
      "Processor": "Custom 8-Core Zen 3",
      "GPU": "RDNA 3, 12 TFLOPS",
      "RAM": "16GB GDDR6",
      "Storage": "1TB NVMe SSD (Expandable)",
      "Resolution": "Up to 8K, Native 4K",
      "Frame Rate": "Up to 120fps",
      "Ray Tracing": "Hardware Accelerated",
      "Optical": "4K UHD Blu-ray",
      "Connectivity": "WiFi 6E, Bluetooth 5.2, Ethernet",
      "Ports": "3x USB-A, 1x USB-C, 2x HDMI 2.1",
      "Dimensions": "15.4 x 4.2 x 10.2 inches",
      "Weight": "9.8 lbs",
      "Warranty": "1 Year"
    }
  },
  {
    id: 24,
    name: "Projector 4K Laser",
    category: "Entertainment",
    subcategory: "Projectors",
    brand: "LG",
    price: 599.99,
    originalPrice: 799.99,
    image: "logo and bg imagies/projector.jpg",
    rating: 4.7,
    reviews: 234,
    badge: "25% OFF",
    badgeType: "sale",
    description: "Compact 4K laser projector with smart OS and 150\" projection.",
    features: ["4K Laser", "Smart OS", "Auto Keystone", "150\" Screen", "HDR10"],
    inStock: true,
    detailedSpecs: {
      "Resolution": "3840 x 2160 (4K)",
      "Technology": "DLP Laser",
      "Brightness": "2500 ANSI Lumens",
      "Contrast": "2,000,000:1",
      "Screen Size": "40\" - 150\"",
      "Throw Ratio": "1.0:1",
      "Keystone": "Auto Vertical + Horizontal",
      "Speakers": "10W x 2 Harman Kardon",
      "Smart": "WebOS + Streaming Apps",
      "Connectivity": "2x HDMI, WiFi, Bluetooth, USB",
      "Lamp Life": "20,000 Hours",
      "Dimensions": "13 x 8 x 5 inches",
      "Weight": "6.6 lbs",
      "Warranty": "2 Years"
    }
  },

  {
    id: 25,
    name: "Refrigerator 550L Side-by-Side",
    category: "Home Appliances",
    subcategory: "Refrigerators",
    brand: "Haier",
    price: 899.99,
    originalPrice: 1199.99,
    image: "logo and bg imagies/refrigerator1.jpg",
    rating: 4.7,
    reviews: 234,
    badge: "25% OFF",
    badgeType: "sale",
    description: "550L side-by-side refrigerator with inverter compressor, water dispenser, and multi airflow cooling.",
    features: ["550L Capacity", "Inverter Compressor", "Water Dispenser", "Multi Airflow", "LED Display"],
    inStock: true,
    detailedSpecs: {
      "Capacity": "550 Liters (Fridge 335L + Freezer 215L)",
      "Type": "Side-by-Side",
      "Compressor": "Inverter Linear",
      "Energy Rating": "A++ / 5 Star",
      "Cooling": "Multi Air Flow + Metal Cooling",
      "Refrigerant": "R-600a",
      "Dispenser": "Water + Ice",
      "Shelves": "Tempered Glass, Adjustable",
      "Noise": "39 dB",
      "Dimensions": "35.8 x 27.5 x 69.9 inches",
      "Weight": "220 lbs",
      "Color": "Stainless Steel",
      "Warranty": "10 Years Compressor + 1 Year Parts",
      "Features": "Holiday Mode, Door Alarm, Deodorizer"
    }
  },
  {
    id: 26,
    name: "Refrigerator 350L Double Door",
    category: "Home Appliances",
    subcategory: "Refrigerators",
    brand: "Dawlance",
    price: 549.99,
    originalPrice: 699.99,
    image: "logo and bg imagies/refrigerator4.jpg",
    rating: 4.5,
    reviews: 189,
    badge: "Value Pick",
    badgeType: "sale",
    description: "350L frost-free refrigerator with inverter technology and energy-saving operation.",
    features: ["350L Capacity", "Frost Free", "Inverter Tech", "Energy Saving", "Wide Voltage"],
    inStock: true,
    detailedSpecs: {
      "Capacity": "350 Liters (Fridge 250L + Freezer 100L)",
      "Type": "Double Door, Frost Free",
      "Compressor": "Inverter",
      "Energy Rating": "A+ / 4 Star",
      "Cooling": "360° Uniform Cooling",
      "Refrigerant": "R-600a",
      "Voltage": "Wide Range 130V-300V",
      "Shelves": "Toughened Glass",
      "Noise": "42 dB",
      "Dimensions": "27 x 25 x 66 inches",
      "Weight": "145 lbs",
      "Color": "Chrome Silver",
      "Warranty": "12 Years Compressor + 2 Years Parts"
    }
  },
  {
    id: 27,
    name: "Refrigerator 390L Bottom Mount",
    category: "Home Appliances",
    subcategory: "Refrigerators",
    brand: "Samsung",
    price: 749.99,
    originalPrice: 949.99,
    image: "logo and bg imagies/refrigerator3.jpg",
    rating: 4.8,
    reviews: 567,
    badge: "Best Seller",
    badgeType: "hot",
    description: "390L bottom-mount refrigerator with SpaceMax technology and digital inverter.",
    features: ["390L Capacity", "SpaceMax", "Digital Inverter", "All-Around Cooling", "Power Freeze"],
    inStock: true,
    detailedSpecs: {
      "Capacity": "390 Liters",
      "Type": "Bottom Mount Freezer",
      "Compressor": "Digital Inverter",
      "Energy Rating": "A+++ / 5 Star",
      "Cooling": "All-Around Cooling",
      "SpaceMax": "Thinner Walls, More Space",
      "Power Freeze": "Yes",
      "Power Cool": "Yes",
      "Shelves": "Tempered Glass, Slide & Fold",
      "Display": "External LED",
      "Dimensions": "27.1 x 25.8 x 70.1 inches",
      "Weight": "180 lbs",
      "Warranty": "20 Years Compressor + 2 Years Parts"
    }
  },
  {
    id: 28,
    name: "Refrigerator 668L InstaView",
    category: "Home Appliances",
    subcategory: "Refrigerators",
    brand: "LG",
    price: 1299.99,
    originalPrice: 1599.99,
    image: "logo and bg imagies/refrigerator5.jpg",
    rating: 4.9,
    reviews: 312,
    badge: "Premium",
    badgeType: "new",
    description: "668L InstaView door-in-door refrigerator with craft ice and ThinQ app control.",
    features: ["668L Capacity", "InstaView Door", "Craft Ice", "ThinQ WiFi", "Linear Cooling"],
    inStock: true,
    detailedSpecs: {
      "Capacity": "668 Liters",
      "Type": "Side-by-Side, Door-in-Door",
      "Compressor": "Smart Inverter Linear",
      "Energy Rating": "A++ / 5 Star",
      "InstaView": "Knock Twice to See Inside",
      "Craft Ice": "Slow-Melting Round Ice",
      "Cooling": "Linear Cooling ±0.5°C",
      "UVnano": "Water Dispenser UV Sterilization",
      "Smart": "WiFi + LG ThinQ App",
      "Dimensions": "35.7 x 29.8 x 70.9 inches",
      "Weight": "275 lbs",
      "Warranty": "10 Years Compressor + 2 Years Parts"
    }
  },

  {
    id: 29,
    name: "Inverter AC 1.5 Ton Dawlance",
    category: "Home Appliances",
    subcategory: "Air Conditioners",
    brand: "Dawlance",
    price: 499.99,
    originalPrice: 649.99,
    image: "logo and bg imagies/ac1.jpg",
    rating: 4.6,
    reviews: 278,
    badge: "Energy Saver",
    badgeType: "new",
    description: "1.5 Ton inverter AC with turbo cooling, wide voltage operation, and eco-friendly gas.",
    features: ["Inverter", "Turbo Cool", "Wide Voltage", "R-410A Gas", "Self-Clean"],
    inStock: true,
    detailedSpecs: {
      "Capacity": "1.5 Ton / 18000 BTU",
      "Type": "Split Inverter",
      "Energy Rating": "A++ / 5 Star",
      "Compressor": "Full DC Inverter",
      "Refrigerant": "R-410A Eco-Friendly",
      "Cooling Area": "Up to 280 sq ft",
      "Turbo Mode": "Yes, Rapid Cooling",
      "Voltage Range": "150V - 260V",
      "Noise Indoor": "28 dB",
      "Timer": "24 Hour On/Off",
      "Dimensions Indoor": "34 x 8.5 x 12 inches",
      "Warranty": "5 Years Compressor + 1 Year Parts"
    }
  },
  {
    id: 30,
    name: "Inverter AC 2 Ton WindFree",
    category: "Home Appliances",
    subcategory: "Air Conditioners",
    brand: "Samsung",
    price: 799.99,
    originalPrice: 999.99,
    image: "logo and bg imagies/ac2.jpg",
    rating: 4.8,
    reviews: 456,
    badge: "WindFree",
    badgeType: "hot",
    description: "2 Ton WindFree AC with 23,000 micro holes for draft-free cooling and AI auto mode.",
    features: ["WindFree", "AI Auto", "2 Ton", "Triple Inverter", "WiFi"],
    inStock: true,
    detailedSpecs: {
      "Capacity": "2 Ton / 24000 BTU",
      "Type": "Split Triple Inverter",
      "Energy Rating": "A+++ / 5 Star",
      "WindFree": "23,000 Micro Holes",
      "AI Mode": "Learns your preferences",
      "Compressor": "Digital Inverter 8-Pole",
      "Refrigerant": "R-32",
      "Cooling Area": "Up to 350 sq ft",
      "Noise Indoor": "21 dB",
      "Smart": "WiFi + SmartThings + Voice",
      "Warranty": "10 Years Compressor + 2 Years Parts"
    }
  },
  {
    id: 31,
    name: "Inverter AC 1.5 Ton Dual Cool",
    category: "Home Appliances",
    subcategory: "Air Conditioners",
    brand: "LG",
    price: 649.99,
    originalPrice: 849.99,
    image: "logo and bg imagies/ac3.jpg",
    rating: 4.7,
    reviews: 389,
    badge: "Dual Cool",
    badgeType: "hot",
    description: "1.5 Ton dual inverter AC with 4-way swing, HD filter, and ocean black protection.",
    features: ["Dual Inverter", "4-Way Swing", "HD Filter", "Ocean Black", "ThinQ WiFi"],
    inStock: true,
    detailedSpecs: {
      "Capacity": "1.5 Ton / 18000 BTU",
      "Type": "Split Dual Inverter",
      "Energy Rating": "A+++ / 5 Star",
      "Compressor": "DUAL Inverter",
      "Refrigerant": "R-32",
      "Anti-Corrosion": "Ocean Black Fin",
      "Filter": "HD Filter with Anti-Virus",
      "Swing": "4-Way Auto",
      "Noise Indoor": "24 dB",
      "Smart": "LG ThinQ WiFi",
      "Warranty": "10 Years Compressor + 1 Year Parts"
    }
  },

  {
    id: 32,
    name: "Washing Machine 8kg Front Load",
    category: "Home Appliances",
    subcategory: "Washers & Dryers",
    brand: "Haier",
    price: 449.99,
    originalPrice: 599.99,
    image: "logo and bg imagies/washer.jpg",
    rating: 4.6,
    reviews: 234,
    badge: "25% OFF",
    badgeType: "sale",
    description: "8kg fully automatic front load washer with direct motion motor and antibacterial treatment.",
    features: ["8kg Load", "Direct Motor", "Anti-Bacterial", "15 Programs", "LED Display"],
    inStock: true,
    detailedSpecs: {
      "Capacity": "8 kg",
      "Type": "Front Load Automatic",
      "Motor": "Direct Motion Inverter",
      "Spin Speed": "1200 RPM",
      "Programs": "15 Wash Cycles",
      "Temperature": "Cold - 90°C",
      "Anti-Bacterial": "ABT Self-Clean",
      "Energy": "A++",
      "Noise Wash": "52 dB",
      "Noise Spin": "74 dB",
      "Dimensions": "23.6 x 22.8 x 33.1 inches",
      "Weight": "143 lbs",
      "Warranty": "12 Years Motor + 2 Years Parts"
    }
  },
  {
    id: 33,
    name: "Twin Tub Washer 10kg",
    category: "Home Appliances",
    subcategory: "Washers & Dryers",
    brand: "Dawlance",
    price: 249.99,
    originalPrice: 329.99,
    image: "logo and bg imagies/washer1.jpg",
    rating: 4.3,
    reviews: 456,
    badge: "Budget Pick",
    badgeType: "sale",
    description: "10kg semi-automatic twin tub washing machine with powerful wash and spin.",
    features: ["10kg Capacity", "Twin Tub", "Rust-Free Body", "Powerful Spin", "Water Saver"],
    inStock: true,
    detailedSpecs: {
      "Capacity": "10 kg Wash + 6 kg Spin",
      "Type": "Semi-Automatic Twin Tub",
      "Motor": "Copper Wound",
      "Spin Speed": "1350 RPM",
      "Body": "Rust-Free Plastic",
      "Wash Timer": "0-15 Minutes",
      "Spin Timer": "0-5 Minutes",
      "Water Inlet": "Manual Fill",
      "Dimensions": "30 x 18 x 36 inches",
      "Weight": "55 lbs",
      "Warranty": "2 Years Comprehensive"
    }
  },
  {
    id: 34,
    name: "Washer Dryer 9/6kg Combo",
    category: "Home Appliances",
    subcategory: "Washers & Dryers",
    brand: "Samsung",
    price: 849.99,
    originalPrice: 1099.99,
    image: "logo and bg imagies/washer2.jpg",
    rating: 4.8,
    reviews: 345,
    badge: "Premium",
    badgeType: "new",
    description: "9kg wash / 6kg dry combo with EcoBubble, AI Control, and AddWash door.",
    features: ["EcoBubble", "AI Control", "9/6kg", "AddWash Door", "Steam Hygiene"],
    inStock: true,
    detailedSpecs: {
      "Wash Capacity": "9 kg",
      "Dry Capacity": "6 kg",
      "Type": "Front Load Washer Dryer",
      "Motor": "Digital Inverter",
      "Spin Speed": "1400 RPM",
      "EcoBubble": "Cold Wash Performance",
      "AI Control": "Learns Usage Patterns",
      "AddWash": "Add Items Mid-Cycle",
      "Steam": "Hygiene Steam, Wrinkle Prevention",
      "Programs": "23",
      "Energy": "A",
      "Smart": "WiFi + SmartThings",
      "Warranty": "20 Years Motor + 2 Years Parts"
    }
  },

  {
    id: 35,
    name: "Microwave Oven 30L Convection",
    category: "Kitchen Appliances",
    subcategory: "Microwave Ovens",
    brand: "Haier",
    price: 169.99,
    originalPrice: 219.99,
    image: "logo and bg imagies/Microwave1.jpg",
    rating: 4.5,
    reviews: 267,
    badge: "New",
    badgeType: "new",
    description: "30L convection microwave with 300+ auto-cook menus and multi-stage cooking.",
    features: ["30L Capacity", "Convection", "300+ Menus", "Grill", "Auto Cook"],
    inStock: true,
    detailedSpecs: {
      "Capacity": "30 Liters",
      "Power Output": "900W Microwave + 1300W Convection",
      "Grill": "1100W Quartz",
      "Auto Menus": "301 Indian Recipes",
      "Convection Temp": "Up to 250°C / 480°F",
      "Turntable": "12.5 inch",
      "Control": "Membrane Keypad + Jog Dial",
      "Display": "LED",
      "Warranty": "1 Year Comprehensive",
      "Color": "Black"
    }
  },
  {
    id: 36,
    name: "Microwave Oven 25L Grill",
    category: "Kitchen Appliances",
    subcategory: "Microwave Ovens",
    brand: "Dawlance",
    price: 119.99,
    originalPrice: 159.99,
    image: "logo and bg imagies/Microwave3.jpg",
    rating: 4.4,
    reviews: 345,
    badge: "25% OFF",
    badgeType: "sale",
    description: "25L microwave with grill function, 8 auto menus, and defrost system.",
    features: ["25L", "Grill Function", "8 Auto Menus", "Quick Defrost", "Child Lock"],
    inStock: true,
    detailedSpecs: {
      "Capacity": "25 Liters",
      "Power Output": "800W Microwave",
      "Grill": "1000W",
      "Auto Menus": "8 Preset",
      "Defrost": "Auto by Weight / Time",
      "Turntable": "10.6 inch",
      "Timer": "95 Minutes",
      "Child Lock": "Yes",
      "Dimensions": "19.1 x 14.4 x 11.2 inches",
      "Weight": "26 lbs",
      "Warranty": "1 Year",
      "Color": "Silver"
    }
  },

  {
    id: 37,
    name: "OLED TV 55 Inch 4K",
    category: "Entertainment",
    subcategory: "Televisions",
    brand: "LG",
    price: 1199.99,
    originalPrice: 1499.99,
    image: "logo and bg imagies/tv1.jpg",
    rating: 4.9,
    reviews: 1234,
    badge: "Premium",
    badgeType: "new",
    description: "55\" OLED 4K TV with α9 Gen6 AI processor, Dolby Vision IQ, and webOS.",
    features: ["OLED 4K", "α9 Gen6 AI", "Dolby Vision IQ", "120Hz", "webOS 23"],
    inStock: true,
    detailedSpecs: {
      "Screen": "55 inches OLED evo",
      "Resolution": "3840 x 2160",
      "Processor": "α9 Gen6 AI 4K",
      "HDR": "Dolby Vision IQ, HDR10, HLG",
      "Refresh": "120Hz + VRR + ALLM",
      "Gaming": "G-Sync + FreeSync + Cloud Gaming",
      "Audio": "40W 2.2Ch, Dolby Atmos",
      "HDMI": "4x HDMI 2.1",
      "Smart": "webOS 23 + LG ThinQ",
      "Dimensions": "48.2 x 28 x 1.8 inches",
      "Warranty": "2 Years"
    }
  },
  {
    id: 38,
    name: "LED TV 43 Inch FHD",
    category: "Entertainment",
    subcategory: "Televisions",
    brand: "Haier",
    price: 329.99,
    originalPrice: 449.99,
    image: "logo and bg imagies/tv2.jpg",
    rating: 4.5,
    reviews: 567,
    badge: "27% OFF",
    badgeType: "sale",
    description: "43\" bezel-less FHD smart LED TV with Android TV, Chromecast, and Dolby Audio.",
    features: ["43\" FHD", "Bezel-Less", "Android TV", "Chromecast", "Dolby Audio"],
    inStock: true,
    detailedSpecs: {
      "Screen": "43 inches, Bezel-Less",
      "Resolution": "1920 x 1080 (Full HD)",
      "Panel": "LED / IPS",
      "Smart": "Android TV 11",
      "Chromecast": "Built-in",
      "Audio": "20W, Dolby Audio",
      "HDMI": "3",
      "USB": "2",
      "WiFi": "Dual Band",
      "Bluetooth": "5.0",
      "Dimensions": "38.2 x 22.5 x 3.1 inches",
      "Warranty": "2 Years"
    }
  },
  {
    id: 39,
    name: "LED TV 32 Inch HD",
    category: "Entertainment",
    subcategory: "Televisions",
    brand: "Dawlance",
    price: 199.99,
    originalPrice: 279.99,
    image: "logo and bg imagies/tv3.jpg",
    rating: 4.3,
    reviews: 345,
    badge: "Budget Pick",
    badgeType: "sale",
    description: "32\" HD Smart LED TV with built-in WiFi, screen mirroring, and USB media player.",
    features: ["32\" HD", "Smart TV", "WiFi", "Screen Mirror", "USB Media"],
    inStock: true,
    detailedSpecs: {
      "Screen": "32 inches",
      "Resolution": "1366 x 768 (HD Ready)",
      "Panel": "LED",
      "Smart": "Linux-Based Smart Platform",
      "WiFi": "Built-in",
      "Mirroring": "Screen Share / Miracast",
      "HDMI": "2",
      "USB": "1",
      "Audio": "10W x 2",
      "Dimensions": "28.9 x 17.2 x 3 inches",
      "Warranty": "1 Year"
    }
  },
  {
    id: 40,
    name: "Inverter AC 1 Ton Pearl",
    category: "Home Appliances",
    subcategory: "Air Conditioners",
    brand: "Haier",
    price: 449.99,
    originalPrice: 599.99,
    image: "logo and bg imagies/ac6.jpg",
    rating: 4.6,
    reviews: 234,
    badge: "Hot Deal",
    badgeType: "hot",
    description: "1 Ton pearl inverter AC with UPS compatibility, turbo cool, and anti-bacterial filter.",
    features: ["1 Ton", "Inverter", "UPS Mode", "Turbo Cool", "Anti-Bacterial"],
    inStock: true,
    detailedSpecs: {
      "Capacity": "1 Ton / 12000 BTU",
      "Type": "Split Inverter",
      "Energy Rating": "A++ / 4 Star",
      "Compressor": "Rotary Inverter",
      "Refrigerant": "R-410A",
      "UPS": "Compatible with UPS/Generator",
      "Cooling Area": "Up to 150 sq ft",
      "Anti-Bacterial": "Built-in Filter",
      "Noise Indoor": "30 dB",
      "Warranty": "5 Years Compressor + 1 Year Parts"
    }
  },

  {
    id: 41,
    name: "Refrigerator 600L French Door",
    category: "Home Appliances",
    subcategory: "Refrigerators",
    brand: "Haier",
    price: 1499.99,
    originalPrice: 1899.99,
    image: "logo and bg imagies/refrigerator5.jpg",
    rating: 4.8,
    reviews: 456,
    badge: "Premium",
    badgeType: "new",
    description: "600L French door refrigerator with convertible zone, triple cooling system, and smart inverter compressor.",
    features: ["600L Capacity", "French Door", "Triple Cooling", "Convertible Zone", "Smart Inverter"],
    inStock: true,
    detailedSpecs: {
      "Capacity": "600 Liters (Fridge 420L + Freezer 180L)",
      "Type": "French Door with Bottom Freezer",
      "Compressor": "Smart Inverter Linear",
      "Energy Rating": "A+++ / 5 Star",
      "Cooling": "Triple Zone Cooling",
      "Convertible": "Freezer to Fridge Conversion",
      "Ice Maker": "Automatic Ice & Water Dispenser",
      "Shelves": "Tempered Glass, Spillproof",
      "Noise": "36 dB",
      "Dimensions": "35.8 x 29 x 70 inches",
      "Weight": "265 lbs",
      "Warranty": "10 Years Compressor + 2 Years Parts",
      "Smart Features": "WiFi + Voice Control + Door Alarm"
    }
  },
  {
    id: 42,
    name: "Freezer 200L",
    category: "Home Appliances",
    subcategory: "Refrigerators",
    brand: "Haier",
    price: 299.99,
    originalPrice: 399.99,
    image: "logo and bg imagies/freezer.jpg",
    rating: 4.5,
    reviews: 234,
    badge: "25% OFF",
    badgeType: "sale",
    description: "200L chest freezer with fast freeze function, adjustable thermostat, and energy-efficient operation.",
    features: ["200L Capacity", "Fast Freeze", "Low Energy", "Adjustable Thermostat", "Lock & Key"],
    inStock: true,
    detailedSpecs: {
      "Capacity": "200 Liters / 7 Cu.Ft",
      "Type": "Chest Freezer",
      "Temperature Range": "-18°C to -24°C",
      "Fast Freeze": "Yes, Super Freeze Mode",
      "Defrost": "Manual",
      "Basket": "1 Wire Basket Included",
      "Energy": "A+ Rated",
      "Noise": "42 dB",
      "Dimensions": "37 x 22 x 33 inches",
      "Weight": "88 lbs",
      "Warranty": "5 Years Compressor + 1 Year Parts",
      "Security": "Lock & Key"
    }
  },
  {
    id: 43,
    name: "Window AC 1 Ton",
    category: "Home Appliances",
    subcategory: "Air Conditioners",
    brand: "Haier",
    price: 349.99,
    originalPrice: 449.99,
    image: "logo and bg imagies/ac5.jpg",
    rating: 4.4,
    reviews: 312,
    badge: "Budget Pick",
    badgeType: "sale",
    description: "1 Ton window AC with turbo cooling, anti-bacterial filter, and easy installation design.",
    features: ["1 Ton", "Turbo Cool", "Anti-Bacterial", "Auto Restart", "Sleep Mode"],
    inStock: true,
    detailedSpecs: {
      "Capacity": "1 Ton / 12000 BTU",
      "Type": "Window AC",
      "Energy Rating": "3 Star",
      "Compressor": "Rotary",
      "Refrigerant": "R-32",
      "Cooling Area": "Up to 150 sq ft",
      "Airflow": "3-Way Auto Swing",
      "Noise Indoor": "48 dB",
      "Power": "1100W",
      "Dimensions": "26 x 16 x 22 inches",
      "Weight": "66 lbs",
      "Warranty": "1 Year Comprehensive"
    }
  },
  {
    id: 44,
    name: "Washer 12kg",
    category: "Home Appliances",
    subcategory: "Washers & Dryers",
    brand: "Haier",
    price: 399.99,
    originalPrice: 549.99,
    image: "logo and bg imagies/washer5.jpg",
    rating: 4.6,
    reviews: 278,
    badge: "27% OFF",
    badgeType: "sale",
    description: "12kg fully automatic top load washer with pulsator wash, magic filter, and 8 wash programs.",
    features: ["12kg Load", "Pulsator Wash", "Magic Filter", "8 Programs", "Quick Wash"],
    inStock: true,
    detailedSpecs: {
      "Capacity": "12 kg / 26.4 lbs",
      "Type": "Top Load Automatic",
      "Motor": "Direct Drive",
      "Spin Speed": "720 RPM",
      "Programs": "8 Wash Cycles",
      "Water Level": "Auto Sense",
      "Filter": "Magic Lint Filter",
      "Tub": "Stainless Steel Pulsator",
      "Energy": "A++",
      "Dimensions": "24 x 24 x 40 inches",
      "Weight": "77 lbs",
      "Warranty": "10 Years Motor + 2 Years Parts"
    }
  },
  {
    id: 45,
    name: "Convection Oven 30L Air Fry",
    category: "Kitchen Appliances",
    subcategory: "Microwave Ovens",
    brand: "Haier",
    price: 189.99,
    originalPrice: 249.99,
    image: "logo and bg imagies/microwave3.jpg",
    rating: 4.5,
    reviews: 189,
    badge: "Smart",
    badgeType: "new",
    description: "30L convection oven with air fry function, rotisserie, and 10 auto-cook menus.",
    features: ["30L Capacity", "Air Fry", "Rotisserie", "Convection", "10 Auto Menus"],
    inStock: true,
    detailedSpecs: {
      "Capacity": "30 Liters",
      "Functions": "Microwave + Convection + Grill + Air Fry",
      "Power": "900W Microwave + 1400W Convection",
      "Air Fry": "Yes, up to 200°C",
      "Rotisserie": "Yes, with Fork Included",
      "Auto Menus": "10 Preset Recipes",
      "Turntable": "13 inch Glass",
      "Timer": "90 Minutes",
      "Dimensions": "20 x 16 x 12 inches",
      "Weight": "33 lbs",
      "Warranty": "1 Year",
      "Control": "Digital Touch Panel"
    }
  },
  {
    id: 46,
    name: "Portable AC 12000 BTU",
    category: "Home Appliances",
    subcategory: "Air Conditioners",
    brand: "Haier",
    price: 449.99,
    originalPrice: 599.99,
    image: "logo and bg imagies/ac6.jpg",
    rating: 4.3,
    reviews: 167,
    badge: "Portable",
    badgeType: "new",
    description: "12000 BTU portable AC with dehumidifier, fan mode, and easy-roll casters for any room.",
    features: ["12000 BTU", "Portable", "Dehumidifier", "3-in-1", "Remote Control"],
    inStock: true,
    detailedSpecs: {
      "Capacity": "12000 BTU",
      "Type": "Portable Floor AC",
      "Modes": "Cool + Dehumidify + Fan",
      "Dehumidifier": "60 Pints/Day",
      "Coverage": "Up to 400 sq ft",
      "Refrigerant": "R-410A",
      "Noise": "52 dB",
      "Power": "1250W",
      "Exhaust Hose": "5 ft Included",
      "Dimensions": "17 x 15 x 30 inches",
      "Weight": "77 lbs",
      "Warranty": "1 Year",
      "Casters": "4 Easy-Roll Wheels"
    }
  },
  {
    id: 47,
    name: "Cordless Vacuum 200AW Jet",
    category: "Home Appliances",
    subcategory: "Vacuums",
    brand: "Samsung",
    price: 549.99,
    originalPrice: 749.99,
    image: "logo and bg imagies/vacum1.jpg",
    rating: 4.8,
    reviews: 534,
    badge: "Best Seller",
    badgeType: "hot",
    description: "All-in-one cordless vacuum with Clean Station, Jet Cyclone technology, and 200AW suction.",
    features: ["200AW Suction", "Clean Station", "60 Min Runtime", "Jet Cyclone", "LCD Display"],
    inStock: true,
    detailedSpecs: {
      "Suction Power": "200 AW",
      "Technology": "Jet Cyclone",
      "Runtime": "Up to 60 Minutes",
      "Battery": "Removable Li-ion",
      "Dustbin": "0.5L (Robot) + Clean Station Auto-Empty",
      "Filtration": "5-Layer HEPA",
      "Weight": "6.2 lbs",
      "Display": "LCD with Battery & Mode",
      "Accessories": "6 Cleaning Tools",
      "Warranty": "2 Years",
      "Charging": "3.5 Hours",
      "Modes": "Jet / Normal / MIN"
    }
  },
  {
    id: 48,
    name: "Wireless Earbuds ANC",
    category: "Entertainment",
    subcategory: "Headphones",
    brand: "Samsung",
    price: 179.99,
    originalPrice: 229.99,
    image: "logo and bg imagies/headphone.jpg",
    rating: 4.7,
    reviews: 1892,
    badge: "Hot",
    badgeType: "hot",
    description: "Premium wireless earbuds with Intelligent ANC, 24-bit Hi-Fi audio, and 360 Audio support.",
    features: ["Intelligent ANC", "24-bit Hi-Fi", "360 Audio", "IPX7", "29Hr Battery"],
    inStock: true,
    detailedSpecs: {
      "Driver": "2-way (Woofer + Tweeter)",
      "Audio": "24-bit Hi-Fi, 360 Audio",
      "ANC": "Intelligent Active Noise Cancellation",
      "Ambient": "3-Level Ambient Sound",
      "Battery Earbuds": "5 Hours (ANC On)",
      "Battery Total": "29 Hours with Case",
      "Charging": "USB-C + Wireless",
      "Quick Charge": "5 Min = 1 Hour",
      "Water Resistance": "IPX7 Earbuds",
      "Connectivity": "Bluetooth 5.3",
      "Weight": "5.5g per Earbud",
      "Warranty": "1 Year"
    }
  },
  {
    id: 49,
    name: "QLED TV 65 Inch 4K",
    category: "Entertainment",
    subcategory: "Televisions",
    brand: "Samsung",
    price: 1299.99,
    originalPrice: 1699.99,
    image: "logo and bg imagies/tv6.jpg",
    rating: 4.9,
    reviews: 2134,
    badge: "Premium",
    badgeType: "new",
    description: "65\" Neo QLED with Quantum Matrix Technology, Neural Quantum Processor 4K, and Object Tracking Sound+",
    features: ["Neo QLED", "Quantum Matrix", "Neural 4K AI", "144Hz Gaming", "OTS+"],
    inStock: true,
    detailedSpecs: {
      "Screen Size": "65 inches",
      "Resolution": "3840 x 2160 (4K UHD)",
      "Panel": "Neo QLED (Mini LED)",
      "Processor": "Neural Quantum Processor 4K",
      "HDR": "Quantum HDR 32X",
      "Refresh Rate": "144Hz VRR",
      "Gaming": "Game Bar, FreeSync Premium Pro",
      "Audio": "60W 4.2.2Ch Object Tracking Sound+",
      "Smart": "Tizen OS + SmartThings",
      "HDMI": "4x HDMI 2.1",
      "Dimensions": "57.1 x 32.9 x 1.1 inches",
      "Warranty": "2 Years"
    }
  },
  {
    id: 50,
    name: "Gaming Monitor 32 Inch 240Hz",
    category: "Entertainment",
    subcategory: "Gaming",
    brand: "Samsung",
    price: 599.99,
    originalPrice: 799.99,
    image: "logo and bg imagies/gaming1.jpg",
    rating: 4.8,
    reviews: 876,
    badge: "Gamer's Choice",
    badgeType: "hot",
    description: "32\" curved QLED gaming monitor with 240Hz refresh rate, 1ms response, and 1000R curvature.",
    features: ["240Hz", "1ms Response", "QLED", "1000R Curve", "G-Sync Compatible"],
    inStock: true,
    detailedSpecs: {
      "Screen Size": "32 inches",
      "Resolution": "2560 x 1440 (QHD)",
      "Panel": "VA QLED",
      "Curvature": "1000R",
      "Refresh Rate": "240Hz",
      "Response Time": "1ms (GTG)",
      "HDR": "HDR600",
      "Sync": "G-Sync Compatible + FreeSync Premium Pro",
      "Brightness": "600 nits",
      "Ports": "2x HDMI 2.0, 1x DP 1.4, USB Hub",
      "Stand": "Height, Tilt, Swivel Adjustable",
      "Warranty": "3 Years"
    }
  },
  {
    id: 51,
    name: "Frame TV 50 Inch Art",
    category: "Entertainment",
    subcategory: "Televisions",
    brand: "Samsung",
    price: 999.99,
    originalPrice: 1299.99,
    image: "logo and bg imagies/tv3.jpg",
    rating: 4.7,
    reviews: 678,
    badge: "Art Mode",
    badgeType: "new",
    description: "50\" QLED TV that transforms into art when off, with matte display and customizable bezels.",
    features: ["Art Mode", "Matte Display", "QLED 4K", "Anti-Reflection", "Slim Fit Wall Mount"],
    inStock: true,
    detailedSpecs: {
      "Screen Size": "50 inches",
      "Resolution": "3840 x 2160 (4K UHD)",
      "Panel": "QLED with Matte Finish",
      "Art Mode": "Motion Sensor + Art Store (1500+ artworks)",
      "HDR": "Quantum HDR",
      "Processor": "Quantum Processor 4K",
      "Anti-Reflection": "Yes",
      "Audio": "40W 2.0Ch",
      "Bezel": "Customizable (Sold Separately)",
      "Mount": "Slim Fit Wall Mount Included",
      "Smart": "Tizen + SmartThings",
      "Warranty": "2 Years"
    }
  },
  {
    id: 52,
    name: "Oven Range Double Door",
    category: "Kitchen Appliances",
    subcategory: "Cookers",
    brand: "Samsung",
    price: 1199.99,
    originalPrice: 1599.99,
    image: "logo and bg imagies/microwave2.jpg",
    rating: 4.6,
    reviews: 345,
    badge: "25% OFF",
    badgeType: "sale",
    description: "Flex Duo electric range with dual oven doors, air fry, and Wi-Fi connectivity.",
    features: ["Flex Duo", "Air Fry", "WiFi", "Self Clean", "5 Burners"],
    inStock: true,
    detailedSpecs: {
      "Type": "Electric Range",
      "Total Capacity": "6.3 Cu.Ft",
      "Flex Duo": "Upper 2.7 + Lower 3.6 Cu.Ft",
      "Cooktop": "5 Element Smooth Top",
      "Burner Power": "3600W Triple Ring",
      "Air Fry": "Built-in Air Fry Mode",
      "Convection": "True Convection",
      "Self Clean": "Steam + High Heat",
      "Smart": "WiFi + SmartThings + Voice Control",
      "Dimensions": "29.9 x 26 x 47.3 inches",
      "Warranty": "1 Year",
      "Finish": "Stainless Steel"
    }
  },
  {
    id: 53,
    name: "Air Purifier 620sqft 360",
    category: "Home Appliances",
    subcategory: "Air Purifiers",
    brand: "LG",
    price: 549.99,
    originalPrice: 699.99,
    image: "logo and bg imagies/airpurifier.jpg",
    rating: 4.8,
    reviews: 423,
    badge: "360° Clean",
    badgeType: "hot",
    description: "360° air purifier with Clean Booster fan, PM1.0 sensor, and True HEPA filtration.",
    features: ["360° Purification", "Clean Booster", "PM1.0 Sensor", "True HEPA", "ThinQ WiFi"],
    inStock: true,
    detailedSpecs: {
      "Coverage": "Up to 620 sq ft",
      "CADR": "310 CFM",
      "Filtration": "360° True HEPA + Deodorization",
      "Particle Detection": "PM1.0 / PM2.5 / PM10 + Gas",
      "Clean Booster": "Rotating Fan for Wide Coverage",
      "Display": "LED Air Quality Indicator",
      "Noise": "25-48 dB",
      "Power": "65W Max",
      "Smart": "LG ThinQ WiFi + Voice",
      "Filter Life": "12 Months",
      "Dimensions": "14 x 14 x 23 inches",
      "Warranty": "2 Years"
    }
  },
  {
    id: 54,
    name: "Wireless Earbuds Dolby",
    category: "Entertainment",
    subcategory: "Headphones",
    brand: "LG",
    price: 199.99,
    originalPrice: 249.99,
    image: "logo and bg imagies/earbuds.jpg",
    rating: 4.6,
    reviews: 567,
    badge: "Dolby Atmos",
    badgeType: "new",
    description: "Premium earbuds with Dolby Atmos, ANC, UVnano charging case, and Dolby Head Tracking.",
    features: ["Dolby Atmos", "Head Tracking", "ANC", "UVnano Case", "36Hr Battery"],
    inStock: true,
    detailedSpecs: {
      "Driver": "11mm Graphene",
      "Audio": "Dolby Atmos + Head Tracking",
      "ANC": "Adaptive Active Noise Cancellation",
      "Battery Earbuds": "9 Hours (ANC Off)",
      "Battery Total": "36 Hours with Case",
      "UVnano": "UV Sterilization in Case",
      "Water Resistance": "IPX4",
      "Charging": "USB-C + Wireless",
      "Quick Charge": "5 Min = 1 Hour",
      "Connectivity": "Bluetooth 5.3",
      "Warranty": "1 Year",
      "Mic": "6 Mics for Calls"
    }
  },
  {
    id: 55,
    name: "Gaming Monitor 27 Inch 4K",
    category: "Entertainment",
    subcategory: "Gaming",
    brand: "LG",
    price: 699.99,
    originalPrice: 899.99,
    image: "logo and bg imagies/gaming2.jpg",
    rating: 4.9,
    reviews: 432,
    badge: "4K 144Hz",
    badgeType: "hot",
    description: "27\" Nano IPS 4K gaming monitor with 144Hz, 1ms GtG, HDMI 2.1, and G-Sync Compatible.",
    features: ["4K 144Hz", "Nano IPS", "1ms GtG", "HDMI 2.1", "G-Sync"],
    inStock: true,
    detailedSpecs: {
      "Screen Size": "27 inches",
      "Resolution": "3840 x 2160 (4K UHD)",
      "Panel": "Nano IPS",
      "Refresh Rate": "144Hz (OC 160Hz)",
      "Response Time": "1ms GtG",
      "HDR": "VESA DisplayHDR 600",
      "Sync": "NVIDIA G-Sync Compatible",
      "Color": "98% DCI-P3, 10-bit",
      "HDMI": "2x HDMI 2.1 (4K/120Hz)",
      "DisplayPort": "1x DP 1.4",
      "Stand": "Height, Pivot, Tilt, Swivel",
      "Warranty": "3 Years"
    }
  },
  {
    id: 56,
    name: "TV 55 Inch 4K",
    category: "Entertainment",
    subcategory: "Televisions",
    brand: "LG",
    price: 649.99,
    originalPrice: 849.99,
    image: "logo and bg imagies/tv3.jpg",
    rating: 4.6,
    reviews: 789,
    badge: "24% OFF",
    badgeType: "sale",
    description: "55\" NanoCell TV with α7 Gen5 AI Processor, Dolby Vision IQ, and webOS 23.",
    features: ["NanoCell", "α7 Gen5 AI", "Dolby Vision IQ", "120Hz", "Game Optimizer"],
    inStock: true,
    detailedSpecs: {
      "Screen Size": "55 inches",
      "Resolution": "3840 x 2160 (4K UHD)",
      "Panel": "NanoCell IPS",
      "Processor": "α7 Gen5 AI 4K",
      "HDR": "Dolby Vision IQ, HDR10, HLG",
      "Refresh Rate": "120Hz",
      "Gaming": "Game Optimizer, ALLM, VRR",
      "Audio": "20W 2.0Ch, Dolby Atmos",
      "Smart": "webOS 23 + LG ThinQ",
      "HDMI": "4x (2 HDMI 2.1)",
      "Dimensions": "48.5 x 28.1 x 2.3 inches",
      "Warranty": "2 Years"
    }
  },
  {
    id: 57,
    name: "Portable Speaker 360 Sound",
    category: "Entertainment",
    subcategory: "Speakers",
    brand: "LG",
    price: 299.99,
    originalPrice: 399.99,
    image: "logo and bg imagies/speaker.jpg",
    rating: 4.7,
    reviews: 345,
    badge: "360° Sound",
    badgeType: "hot",
    description: "Omnidirectional portable speaker with mood lighting, 10-hour battery, and IP54 rating.",
    features: ["360° Audio", "Mood Lighting", "10Hr Battery", "IP54", "Bluetooth 5.0"],
    inStock: true,
    detailedSpecs: {
      "Output": "120W RMS",
      "Drivers": "Dual Passive Radiator + Full Range",
      "Audio": "360° Omnidirectional",
      "Lighting": "Mood Lighting (4 Modes)",
      "Battery": "10 Hours Playback",
      "Charging": "USB-C, 4 Hours",
      "Water Resistance": "IP54",
      "Bluetooth": "5.0",
      "Multi-Speaker": "Wireless Party Link",
      "Dimensions": "7.9 x 7.9 x 13.3 inches",
      "Weight": "6.4 lbs",
      "Warranty": "1 Year"
    }
  },
  {
    id: 58,
    name: "Vacuum 200W Kompressor",
    category: "Home Appliances",
    subcategory: "Vacuums",
    brand: "LG",
    price: 499.99,
    originalPrice: 649.99,
    image: "logo and bg imagies/vacum3.jpg",
    rating: 4.7,
    reviews: 398,
    badge: "Kompressor",
    badgeType: "new",
    description: "Cordless stick vacuum with Kompressor technology that compresses dust for 2.4x more capacity.",
    features: ["Kompressor", "200W Suction", "80 Min Runtime", "Dual Battery", "Power Drive Mop"],
    inStock: true,
    detailedSpecs: {
      "Suction": "200W (Turbo Mode)",
      "Kompressor": "2.4x More Dust Capacity",
      "Runtime": "Up to 80 Minutes (Dual Battery)",
      "Battery": "2x Removable Li-ion",
      "Dustbin": "0.44L",
      "Filtration": "5-Stage HEPA",
      "Mopping": "Power Drive Mop Included",
      "Weight": "5.9 lbs",
      "Display": "LED Runtime Indicator",
      "Accessories": "8 Cleaning Tools",
      "Warranty": "2 Years",
      "Charging": "Wall Mount Station"
    }
  },
  {
    id: 59,
    name: "Freezer 300L",
    category: "Home Appliances",
    subcategory: "Refrigerators",
    brand: "Dawlance",
    price: 449.99,
    originalPrice: 599.99,
    image: "logo and bg imagies/freezer.jpg",
    rating: 4.4,
    reviews: 189,
    badge: "25% OFF",
    badgeType: "sale",
    description: "300L vertical freezer with 7 drawers, fast freeze, and no-frost technology.",
    features: ["300L Capacity", "7 Drawers", "No Frost", "Fast Freeze", "Door Alarm"],
    inStock: true,
    detailedSpecs: {
      "Capacity": "300 Liters / 10.6 Cu.Ft",
      "Type": "Vertical Freezer",
      "Drawers": "7 Transparent Drawers",
      "Cooling": "No Frost",
      "Fast Freeze": "Super Freeze Mode",
      "Temperature": "Digital Control -14°C to -24°C",
      "Alarm": "Door Open Alarm",
      "Energy": "A+ Rated",
      "Noise": "42 dB",
      "Dimensions": "23 x 24 x 67 inches",
      "Weight": "132 lbs",
      "Warranty": "10 Years Compressor + 2 Years Parts"
    }
  },
  {
    id: 60,
    name: "Microwave Oven 30L Inverter",
    category: "Kitchen Appliances",
    subcategory: "Microwave Ovens",
    brand: "Dawlance",
    price: 179.99,
    originalPrice: 229.99,
    image: "logo and bg imagies/microwave4.jpg",
    rating: 4.5,
    reviews: 267,
    badge: "Inverter Tech",
    badgeType: "new",
    description: "30L inverter microwave with even cooking, defrost sensor, and 10 power levels.",
    features: ["Inverter Tech", "30L", "Sensor Defrost", "10 Power Levels", "Child Lock"],
    inStock: true,
    detailedSpecs: {
      "Capacity": "30 Liters",
      "Technology": "Inverter (Even Cooking)",
      "Power Output": "1000W",
      "Power Levels": "10",
      "Sensor": "Auto Defrost + Reheat",
      "Auto Menu": "6 Preset",
      "Turntable": "12.8 inch Glass",
      "Timer": "99 Minutes",
      "Display": "LED Digital",
      "Dimensions": "20 x 15 x 12 inches",
      "Weight": "30 lbs",
      "Warranty": "1 Year"
    }
  },
  {
    id: 61,
    name: "Air Cooler 65L Room",
    category: "Home Appliances",
    subcategory: "Fans",
    brand: "Dawlance",
    price: 199.99,
    originalPrice: 279.99,
    image: "logo and bg imagies/aircooler.jpg",
    rating: 4.3,
    reviews: 345,
    badge: "Budget Cooling",
    badgeType: "sale",
    description: "65L evaporative air cooler with ice compartment, 3 speed settings, and large wheels.",
    features: ["65L Tank", "Ice Compartment", "3 Speeds", "Honeycomb Pads", "Remote Control"],
    inStock: true,
    detailedSpecs: {
      "Tank Capacity": "65 Liters",
      "Type": "Evaporative Air Cooler",
      "Cooling Pads": "Honeycomb",
      "Ice Compartment": "Yes",
      "Airflow": "4500 CFM",
      "Coverage": "Up to 500 sq ft",
      "Speed Settings": "3 + Natural Mode",
      "Timer": "7.5 Hours",
      "Remote": "Yes",
      "Wheels": "Heavy Duty Casters",
      "Dimensions": "24 x 17 x 46 inches",
      "Warranty": "1 Year"
    }
  },
  {
    id: 62,
    name: "Blender 700W 2-in-1",
    category: "Kitchen Appliances",
    subcategory: "Blenders",
    brand: "Dawlance",
    price: 69.99,
    originalPrice: 99.99,
    image: "logo and bg imagies/blender.jpg",
    rating: 4.4,
    reviews: 423,
    badge: "30% OFF",
    badgeType: "sale",
    description: "700W 2-in-1 blender with 1.5L glass jar, dry mill, and stainless steel blades.",
    features: ["700W Motor", "2-in-1", "Glass Jar", "Dry Mill", "2 Speeds + Pulse"],
    inStock: true,
    detailedSpecs: {
      "Power": "700 Watts",
      "Jar Capacity": "1.5 Liters Glass",
      "Dry Mill": "300ml Stainless Steel",
      "Blades": "6-Blade Stainless Steel",
      "Speeds": "2 + Pulse",
      "Jar Type": "Heat Resistant Glass",
      "Safety": "Overheat Protection",
      "Cord Length": "1.2m",
      "Dimensions": "7 x 7 x 15 inches",
      "Weight": "6 lbs",
      "Warranty": "2 Years",
      "Color": "Black / Silver"
    }
  },
  {
    id: 63,
    name: "Water Heater 50L Electric",
    category: "Home Appliances",
    subcategory: "Water Heaters",
    brand: "Dawlance",
    price: 179.99,
    originalPrice: 249.99,
    image: "logo and bg imagies/water heater.jpg",
    rating: 4.5,
    reviews: 234,
    badge: "Energy Saver",
    badgeType: "new",
    description: "50L electric water heater with glass-lined tank, adjustable thermostat, and fast heating.",
    features: ["50L Capacity", "Glass Lined", "Fast Heating", "Adjustable Temp", "Safety Valve"],
    inStock: true,
    detailedSpecs: {
      "Capacity": "50 Liters / 13 Gallons",
      "Type": "Electric Storage Water Heater",
      "Tank": "Glass Lined Steel",
      "Heating Element": "2000W Copper",
      "Temperature Range": "35°C - 75°C",
      "Thermostat": "Adjustable Dial",
      "Recovery": "45 Min (25°C to 65°C)",
      "Safety": "Pressure Relief Valve + Thermal Cutoff",
      "Mounting": "Vertical Wall Mount",
      "Dimensions": "17 x 17 x 24 inches",
      "Weight": "44 lbs",
      "Warranty": "5 Years Tank + 1 Year Parts"
    }
  },
  {
    id: 64,
    name: "Semi Auto Washer 14kg",
    category: "Home Appliances",
    subcategory: "Washers & Dryers",
    brand: "Dawlance",
    price: 329.99,
    originalPrice: 449.99,
    image: "logo and bg imagies/washer2.jpg",
    rating: 4.3,
    reviews: 312,
    badge: "27% OFF",
    badgeType: "sale",
    description: "14kg semi-automatic twin tub washer with powerful pulsator and rust-free body.",
    features: ["14kg Wash", "8kg Spin", "Rust Free", "Powerful Motor", "Water Saver"],
    inStock: true,
    detailedSpecs: {
      "Wash Capacity": "14 kg",
      "Spin Capacity": "8 kg",
      "Type": "Semi-Automatic Twin Tub",
      "Pulsator": "Powerful Active Pulsator",
      "Spin Speed": "1350 RPM",
      "Body": "Rust-Free Plastic",
      "Wash Timer": "0-15 Minutes",
      "Spin Timer": "0-5 Minutes",
      "Water Inlet": "Manual Fill",
      "Drain": "Auto Drain",
      "Dimensions": "34 x 20 x 40 inches",
      "Warranty": "2 Years Comprehensive"
    }
  },
  {
    id: 65,
    name: "Air Fryer XXL 7.3L",
    category: "Kitchen Appliances",
    subcategory: "Air Fryers",
    brand: "Philips",
    price: 249.99,
    originalPrice: 329.99,
    image: "logo and bg imagies/airfry.jpg",
    rating: 4.9,
    reviews: 1234,
    badge: "Best Seller",
    badgeType: "hot",
    description: "XXL capacity air fryer with Smart Sensing technology, fat removal, and digital display.",
    features: ["XXL 7.3L", "Smart Sensing", "Fat Removal", "Keep Warm", "5 Presets"],
    inStock: true,
    detailedSpecs: {
      "Capacity": "7.3 Liters / 3 lbs Food",
      "Technology": "Rapid Air + Smart Sensing",
      "Power": "2225 Watts",
      "Temperature": "80°C - 200°C",
      "Timer": "60 Minutes",
      "Presets": "5 (Fries, Chicken, Fish, Meat, Cake)",
      "Fat Removal": "Removes Excess Fat",
      "Keep Warm": "30 Minutes",
      "Dishwasher Safe": "Yes, All Parts",
      "Dimensions": "12.5 x 16.5 x 12 inches",
      "Warranty": "2 Years",
      "App": "NutriU App with 200+ Recipes"
    }
  },
  {
    id: 66,
    name: "Electric Toothbrush Smart AI",
    category: "Personal Care",
    subcategory: "Oral Care",
    brand: "Philips",
    price: 199.99,
    originalPrice: 279.99,
    image: "logo and bg imagies/tooth brush.jpg",
    rating: 4.8,
    reviews: 876,
    badge: "Premium",
    badgeType: "new",
    description: "Smart sonic toothbrush with AI-powered app, pressure sensor, and 4 brush heads.",
    features: ["Smart Sensor", "AI App", "5 Modes", "Pressure Alert", "Glass Charger"],
    inStock: true,
    detailedSpecs: {
      "Technology": "Sonic, 62,000 strokes/min",
      "Modes": "5 (Clean, White+, Gum Health, Deep Clean+, Sensitive)",
      "Smart Sensor": "Location + Scrubbing + Coverage",
      "App": "Sonicare App with AI Coaching",
      "Pressure Sensor": "Yes, LED + Haptic Alert",
      "Battery": "Li-ion, 14 Days",
      "Charging": "Glass Charger + USB Case",
      "Brush Heads": "4 Premium Heads Included",
      "Timer": "2 Min Quad-Pacer",
      "Travel Case": "USB Charging Case",
      "Warranty": "2 Years"
    }
  },
  {
    id: 67,
    name: "Trimmer OneBlade Face Body",
    category: "Personal Care",
    subcategory: "Shavers",
    brand: "Philips",
    price: 79.99,
    originalPrice: 99.99,
    image: "logo and bg imagies/trimmer.jpg",
    rating: 4.7,
    reviews: 1567,
    badge: "Versatile",
    badgeType: "hot",
    description: "Hybrid electric trimmer and shaver for face and body with 14 length settings.",
    features: ["Trim + Shave", "Face & Body", "14 Lengths", "90 Min Battery", "Wet & Dry"],
    inStock: true,
    detailedSpecs: {
      "Blades": "Dual-Sided Blade (OneBlade Tech)",
      "Length Settings": "14 (0.4mm - 10mm)",
      "Attachments": "Face Comb + Body Comb + Skin Guard",
      "Battery": "90 Minutes Runtime",
      "Charge Time": "1 Hour",
      "Wet & Dry": "Yes, Shower Safe",
      "Dual Sided": "Yes, for Body",
      "Skin Guard": "For Sensitive Areas",
      "LED": "Battery Indicator",
      "Warranty": "2 Years",
      "Blade Life": "4 Months (Replaceable)"
    }
  },
  {
    id: 68,
    name: "IPL Hair Removal Device",
    category: "Personal Care",
    subcategory: "Hair Care",
    brand: "Philips",
    price: 399.99,
    originalPrice: 549.99,
    image: "logo and bg imagies/hairremover.jpg",
    rating: 4.6,
    reviews: 456,
    badge: "27% OFF",
    badgeType: "sale",
    description: "IPL hair removal device with SenseIQ technology, skin tone sensor, and cordless use.",
    features: ["IPL Tech", "SenseIQ", "450,000 Flashes", "5 Settings", "Cordless"],
    inStock: true,
    detailedSpecs: {
      "Technology": "IPL (Intense Pulsed Light)",
      "SenseIQ": "Auto Skin Tone Adaptation",
      "Flash Count": "450,000 (20 Years of Use)",
      "Intensity": "5 Settings",
      "Attachments": "Body + Face + Precision",
      "Treatment Time": "Full Body in 30 Min",
      "Cordless": "Yes, 40 Min Runtime",
      "Skin Tone Sensor": "SmartSkin",
      "Skin Tones": "Light to Medium-Dark",
      "Results": "Up to 92% Hair Reduction in 3 Treatments",
      "Warranty": "2 Years"
    }
  },
  {
    id: 69,
    name: "Espresso Machine LatteGo",
    category: "Kitchen Appliances",
    subcategory: "Coffee Makers",
    brand: "Philips",
    price: 899.99,
    originalPrice: 1199.99,
    image: "logo and bg imagies/coffiemaker1.jpg",
    rating: 4.8,
    reviews: 567,
    badge: "Premium",
    badgeType: "new",
    description: "Fully automatic espresso machine with LatteGo milk system, 12 coffee varieties, and ceramic grinder.",
    features: ["LatteGo", "12 Coffees", "Ceramic Grinder", "Touch Display", "AquaClean"],
    inStock: true,
    detailedSpecs: {
      "Coffee Varieties": "12 (Espresso, Americano, Latte, Cappuccino, etc.)",
      "Milk System": "LatteGo (2-Part, Easy Clean)",
      "Grinder": "Ceramic, 12 Settings",
      "Brew Group": "Removable, Easy Clean",
      "Water Tank": "1.8 Liters",
      "Bean Container": "275g",
      "Pressure": "15 Bar",
      "Display": "Color Touchscreen",
      "Profiles": "4 User Profiles",
      "Filter": "AquaClean (5000 Cups No Descaling)",
      "Dimensions": "9.6 x 17.5 x 14.5 inches",
      "Warranty": "2 Years"
    }
  },
  {
    id: 70,
    name: "Smart Light Kit 4 Bulbs",
    category: "Home Appliances",
    subcategory: "Smart Lighting",
    brand: "Philips",
    price: 159.99,
    originalPrice: 199.99,
    image: "logo and bg imagies/smart lighing.jpg",
    rating: 4.7,
    reviews: 2345,
    badge: "Smart Home",
    badgeType: "hot",
    description: "Smart LED starter kit with 4 color bulbs, Hue Bridge, and app control for unlimited colors.",
    features: ["16M Colors", "4 Bulbs", "Hue Bridge", "Voice Control", "Schedules"],
    inStock: true,
    detailedSpecs: {
      "Bulbs Included": "4 x E26 Color Ambiance",
      "Lumens": "800 lm per Bulb",
      "Colors": "16 Million Colors + Tunable White",
      "Bridge": "Hue Bridge Included (Controls 50 Lights)",
      "Connectivity": "Zigbee + WiFi (via Bridge)",
      "Voice": "Alexa, Google, Siri",
      "App": "Philips Hue App (iOS/Android)",
      "Schedules": "Timers, Routines, Wake-Up",
      "Energy": "9W (60W Equivalent)",
      "Lifespan": "25,000 Hours",
      "Warranty": "2 Years"
    }
  }
];

var TECHWAVE_BRANDS = [
  { id: 'haier', name: 'Haier', country: 'China', logo: 'H', color: ['#e74c3c', '#c0392b'], tagline: 'Inspired Living' },
  { id: 'samsung', name: 'Samsung', country: 'South Korea', logo: 'S', color: ['#1428a0', '#0b1f6f'], tagline: 'Do What You Can\'t' },
  { id: 'lg', name: 'LG', country: 'South Korea', logo: 'LG', color: ['#a50034', '#7a0028'], tagline: 'Life\'s Good' },
  { id: 'dawlance', name: 'Dawlance', country: 'Pakistan', logo: 'D', color: ['#e67e22', '#d35400'], tagline: 'Reliable Hai' },
  { id: 'philips', name: 'Philips', country: 'Netherlands', logo: 'P', color: ['#0b5ed7', '#0947a6'], tagline: 'Innovation and You' }
];

var TECHWAVE_SUBCATEGORIES = [
  { id: 'refrigerators', name: 'Refrigerators', icon: 'fa-snowflake', category: 'Home Appliances' },
  { id: 'air-conditioners', name: 'Air Conditioners', icon: 'fa-wind', category: 'Home Appliances' },
  { id: 'washers-dryers', name: 'Washers & Dryers', icon: 'fa-tshirt', category: 'Home Appliances' },
  { id: 'microwave-ovens', name: 'Microwave Ovens', icon: 'fa-fire-burner', category: 'Kitchen Appliances' },
  { id: 'televisions', name: 'Televisions', icon: 'fa-tv', category: 'Entertainment' },
  { id: 'vacuums', name: 'Vacuums', icon: 'fa-broom', category: 'Home Appliances' },
  { id: 'blenders', name: 'Blenders', icon: 'fa-blender', category: 'Kitchen Appliances' },
  { id: 'air-fryers', name: 'Air Fryers', icon: 'fa-utensils', category: 'Kitchen Appliances' },
  { id: 'coffee-makers', name: 'Coffee Makers', icon: 'fa-mug-hot', category: 'Kitchen Appliances' },
  { id: 'hair-care', name: 'Hair Care', icon: 'fa-spa', category: 'Personal Care' },
  { id: 'shavers', name: 'Shavers & Trimmers', icon: 'fa-cut', category: 'Personal Care' },
  { id: 'speakers', name: 'Speakers', icon: 'fa-volume-up', category: 'Entertainment' },
  { id: 'headphones', name: 'Headphones', icon: 'fa-headphones', category: 'Entertainment' },
  { id: 'gaming', name: 'Gaming', icon: 'fa-gamepad', category: 'Entertainment' },
  { id: 'water-heaters', name: 'Water Heaters', icon: 'fa-fire-flame-simple', category: 'Home Appliances' },
  { id: 'smart-lighting', name: 'Smart Lighting', icon: 'fa-lightbulb', category: 'Home Appliances' },
  { id: 'cookers', name: 'Cookers & Ranges', icon: 'fa-fire-burner', category: 'Kitchen Appliances' },
  { id: 'air-purifiers', name: 'Air Purifiers', icon: 'fa-wind', category: 'Home Appliances' },
  { id: 'fans', name: 'Fans & Coolers', icon: 'fa-fan', category: 'Home Appliances' },
  { id: 'oral-care', name: 'Oral Care', icon: 'fa-tooth', category: 'Personal Care' },
  { id: 'projectors', name: 'Projectors', icon: 'fa-video', category: 'Entertainment' },
  { id: 'mixers', name: 'Mixers', icon: 'fa-blender', category: 'Kitchen Appliances' },
  { id: 'trimmers', name: 'Trimmers', icon: 'fa-scissors', category: 'Personal Care' },
  { id: 'facial-care', name: 'Facial Care', icon: 'fa-face-smile', category: 'Personal Care' }
];

window.TECHWAVE_PRODUCTS = TECHWAVE_PRODUCTS;
window.TECHWAVE_BRANDS = TECHWAVE_BRANDS;
window.TECHWAVE_SUBCATEGORIES = TECHWAVE_SUBCATEGORIES;